### ISSUE TITLE
WAX Eastern-Appeal Apr

### ISSUE THREAD

**Issue by waxeastern** [wax-office-of-inspector-general/waxguilds#304] opened 2022-04-28 02:30 UTC
Dear OIGs,

Regarding to the seed node endpoint, we had 200 open, they got full, we have now increased with another machine so we can open 400 in total. Peering was always there, it just got full. Please kindly check on that.

And for the ecosystem part:

1. For WAX token listing, we've checked with Hoo Exchange, they listed WAX/USDT, a bit wrong on the token name, they will update it asap. 
Token Link: https://hoo.com/innovation/wax-usdt

2. For the cooperation with Token Pocket, they've integrated WAX Chain, here's a screenshot of the wallet page. Actually a lot of our chinese WAX community members have been using it interact with WAX ecosystem, it's a pretty useful tool.

![image](https://user-images.githubusercontent.com/73381583/165663781-9f2d8309-4ac4-4b9b-9a6a-7c04581e3ab2.png)

Thank you OIG and please reach out if you need me provide anything else.
WAX Eastern

**Comment by blocksbarcelona** [comment] 2022-04-29 09:09
Hi, thank you for the update. We score based on the last few weeks availability. We celebrate that the issue is fixed now. Thank you for the extra information on the Ecosystem Development.

**Closed by blocksbarcelona** 2022-04-29 09:09 UTC
